<!-- BEGIN MENUBOTTOM -->
<a class="mmenu2" href="{MENUBOTTOM.HREF}" {MENUBOTTOM.HREFOPTIONS}>{MENUBOTTOM.ITEM}</a>
<!-- END MENUBOTTOM -->
<!-- BEGIN MENUBOTTOMACTIVE -->
<a class="mmenu2" href="{MENUBOTTOMACTIVE.HREF}" {MENUBOTTOMACTIVE.HREFOPTIONS}>{MENUBOTTOMACTIVE.ITEM}</a>
<!-- END MENUBOTTOMACTIVE -->
