<!-- BEGIN NEWSRECORD -->
<h1>{NEWSRECORD.TITLE}</h1>zamieszczono: {NEWSRECORD.DATE}<br /><br />
{NEWSRECORD.DESCSHORT}
{NEWSRECORD.MORE}
<br />
<br />
<!-- END NEWSRECORD -->

<!-- BEGIN NEWSRECORDDETAILS -->
<h1>{NEWSRECORDDETAILS.TITLE}</h1>zamieszczono: {NEWSRECORDDETAILS.DATE}<br /><br />
{NEWSRECORDDETAILS.DESCLONG}
<br />
<br />
<!-- END NEWSRECORDDETAILS -->
<!-- BEGIN NEWSRECORDMORE -->
<br/>
<a class="mm2" href="{NEWSRECORDMORE.LINK}">{NEWSRECORDMORE.MORETEXT}</a>
<!-- END NEWSRECORDMORE -->

<!-- BEGIN NEWSRECORDRIGHT -->

<h2>{NEWSRECORDRIGHT.TITLE}</h2>{NEWSRECORDRIGHT.DATE}<br/><br/>
{NEWSRECORDRIGHT.DESCSHORT}
{NEWSRECORDRIGHT.MORE}
<br/><br/>
<!-- END NEWSRECORDRIGHT -->

<!-- BEGIN NEWSRECORDMORERIGHT -->
<br/>
<a class="mm3" href="{NEWSRECORDMORERIGHT.LINK}">{NEWSRECORDMORERIGHT.MORETEXT}</a>
<!-- END NEWSRECORDMORERIGHT -->