<?
$_LANG_TEXT = array(
	"ERROR" => "Wystąpił błąd systemowy. Skontaktuj się z administratorem.",

	"ENTITIES_BACKTOLIST" => "Back to list",
	
	"PRODUCTS_KEYWORDSTEXT" => "Keywords",
	"PRODUCTS_PRICETEXT" => "Price:",
	"PRODUCTS_PROMOTEXT" => "Promotion:",
	"PRODUCTS_PROMOTIONS" => "Promotions",
	"PRODUCTS_CURRENCY" => "pln",
	"PRODUCTS_ORDERNOW" => "order now",
	
	"COMMON_MORE" => "more",
	"COMMON_READMORE" => "read more",
	"COMMON_SEARCH_INPUTTEXT" => "enter a phrase",
	"COMMON_SEARCH_BUTTONTEXT" => "search",
	"COMMON_SEARCH_RESULTSHEADER" => "Searching results",
	"COMMON_SEARCH_RESULTSTEXT" => "Number of elements matched",
	"COMMON_SEARCH_NORESULTS" => "No matches found",
	"COMMON_DATEAPPEARANCE" => "Date of appearance",
	"COMMON_MENUSIDEHEADERTEXT" => "Products catalogue",
	"COMMON_FOOTERAUTHORTEXT" => "All rights reserved",
	"COMMON_DOWNLOADFILE" => "download file",
	"COMMON_OTHER" => "Others",
	"COMMON_VISIT_COUNTS_TEXT" => "Visits counter:",
	"COMMON_LAST_ACTUALIZATION_TEXT" => "Last act.:",
	"COMMON_PARTNERS" => "Partners",
	
	"GALLERY_RANDOM_HEADER" => "From gallery",
	"GALLERY_RANDOM_MORE" => "enter gallery",
	"GALLERY_MAINDIR" => "Top catalogue",
	
	"NEWS" => "News",
	
	"CONTACTFORM_HEADER" => "Contact form",
	"CONTACTFORM_RECEIVER" => "Receiver",
	"CONTACTFORM_TITLE" => "Message title",
	"CONTACTFORM_SENDER" => "Sender",
	"CONTACTFORM_CONTENT" => "Message content",
	"CONTACTFORM_SEND" => "send",
	"FORM_REQUIRED" => "Required info marked with (*)",
	
	"BASKET" => "Shopping cart",
	"BASKET_SUMMARY_VALUETEXT" => "Total value",
	"BASKET_SUMMARY_QUANTITYTEXT" => "Products quantity",
	"BASKET_SUMMARY_VIEWCART" => "View cart",
	"BASKET_EMPTY" => "Your cart is empty.",
	"BASKET_HEADER_IMAGE" => "Photo",
	"BASKET_HEADER_NAME" => "Name",
	"BASKET_HEADER_PRICE" => "Price",
	"BASKET_HEADER_QUANTITY" => "Quantity",
	"BASKET_HEADER_VALUE" => "Value",
	"BASKET_REMOVEITEM" => "Delete",
	"BASKET_BOTTOM_SUMTEXT" => "Total",
	"BASKET_BOTTOM_DISCOUNTTEXT" => "After included discount %DISCOUNT%% (for products without promotion)",
	"BASKET_CONTINUE" => "Continue",
	"BASKET_MAKEEMPTY" => "Empty cart",
	"BASKET_FINALIZE" => "Checkout",
	"BASKET_RECOUNT" => "Recount",

	"ORDER" => "Realization of the order",
	"ORDER_NEW_OK_HEADER" => "Zamówienie zostało poprawnie wysłane. Na podany adres e-mail wysłano wiadomość.",
	"ORDER_NEW_ERROR_HEADER" => "Error during order process",
	"ORDER_CONFIRM_OK_HEADER" => "Zamówienie zostało potwierdzone poprawnie",
	"ORDER_CONFIRM_ERROR_HEADER" => "Błąd przy potwierdzeniu zamówienia",
	"ORDER_CONFIRM_USERMISMATCH" => "Para użytkownik i nr zamówienia niezgodne",
	"ORDER_CONFIRM_NORESULTS" => "Zamówienie nie istnieje lub zostało już potwierdzone",
	"ORDER_SUMMARY_PRICETEXT" => "Total order costs %TOTALPRICE% + chosen transport method",
	"ORDER_TRANSPORTMETHODTEXT" => "Transport and payment method",
	"ORDER_NOTESTEXT" => "Notes to the order",
	"ORDER_ADDRESDATAHEADERTEXT" => "Address data of the order",
	"ORDER_SENDORDER" => "send the order",
	
	"USER_NOTLOGGEDIN" => "You are not logged in",
	"USER_INVOICE_DATA_HEADER" => "Data for writting out the invoice",
	"USER_FULLNAME" =>"Firstname and surname",
	"USER_COMPANYNAME" => "Company name",
	"USER_NIP" => "Nip",
	"USER_SEND_DATA_HEADER" => "Shipping address",
	"USER_LOGGEDIN_AS" => "You are logged in as",
	"USER_LOGOUTTEXT" => "logout",
	"USER_LOGINTEXT" => "login",
	"USER_LOGINHEADERTEXT" => "Log in",
	"USER_USERTEXT" => "user",
	"USER_PASSWORDTEXT" => "password",
	"USER_REGISTERTEXT" => "registration",
	"USER_REGISTERHEADERTEXT" => "Registration",
	"USER_CHANGEDATATEXT" => "edit user data",
	
	"MODULE_RECOMMEND_HEADER" => "Recommend us!",
	"MODULE_RECOMMEND_TEXT" => "You can recommend our site to your familiars. Just enter their email below.",
	"MODULE_RECOMMEND_EMAILTEXT" => "Enter an email",
	"MODULE_RECOMMEND_SIGNATURETEXT" => "Your signature",
	"MODULE_RECOMMEND_SUBMITTEXT" => "invite",
	"MODULE_RECOMMEND_NEWSLETTERTITLE" => "Invitation to the website",
	"MODULE_RECOMMEND_ALERTOK" => "Thank you for sending.",
	"MODULE_RECOMMEND_ALERTERROR" => "Wrong data entered.",
	
	"MODULE_NEWSLETTER_HEADER" => "Newsletter",
	"MODULE_NEWSLETTER_TEXT" => "If you like to be informed about newness on our site, please enter your email below. Button 'sign off' will delete an email address from the list.",
	"MODULE_NEWSLETTER_NEWSLETTERTITLE" => "Registration in newsletter",
	"MODULE_NEWSLETTER_EMAILTEXT" => "Enter an email",
	"MODULE_NEWSLETTER_UNSUBMITTEXT" => "sign off",
	"MODULE_NEWSLETTER_SUBMITTEXT" => "sign up",
	"MODULE_NEWSLETTER_REGISTEREDALERTOK" => "Registration confirmed.",
	"MODULE_NEWSLETTER_UNALERTOK" => "User signed off.",
	"MODULE_NEWSLETTER_ALERTOK" => "Thank you for sending.",
	"MODULE_NEWSLETTER_ALERTERROR" => "Wrong data entered."	
);
?>