<?
$_LANG_TEXT = array(
	"ERROR" => "Wystąpił‚ błąd systemowy. Skontaktuj się z administratorem.",

	"ENTITIES_BACKTOLIST" => "Powrót do listy",
	
	"PRODUCTS_KEYWORDSTEXT" => "Słowa kluczowe",
	"PRODUCTS_PRICETEXT" => "Cena:",
	"PRODUCTS_PROMOTEXT" => "Promocja:",
	"PRODUCTS_PROMOTIONS" => "Promocje",
	"PRODUCTS_NEWS" => "Nowości",
	"PRODUCTS_CURRENCY" => "pln",
	"PRODUCTS_ORDERNOW" => "zamów teraz",
	"PRODUCTS_CONNECTEDPRODUCTSHEADER" => "Produkty powiązane",
	
	"COMMON_MORE" => "więcej",
	"COMMON_READMORE" => "czytaj więcej",
	"COMMON_SEARCH_INPUTTEXT" => "Szukane wyrażenie",
	"COMMON_SEARCH_BUTTONTEXT" => "szukaj",
	"COMMON_SEARCH_RESULTSHEADER" => "Wyniki wyszukiwania",
	"COMMON_SEARCH_RESULTSTEXT" => "Liczba znalezionych elementów",
	"COMMON_SEARCH_NORESULTS" => "Brak wyników wyszukiwania",
	"COMMON_DATEAPPEARANCE" => "zamieszczono",
	"COMMON_MENUSIDEHEADERTEXT" => "Katalog produktów",
	"COMMON_FOOTERAUTHORTEXT" => "Wszelkie prawa zastrzeżone",
	"COMMON_WRITE" => "zapisz",
	"COMMON_DOWNLOADFILE" => "pobierz plik",
	"COMMON_OTHER" => "Pozostałe",
	"COMMON_VISIT_COUNTS_TEXT" => "Liczba odwiedzin:",
	"COMMON_LAST_ACTUALIZATION_TEXT" => "Ost. aktualizacja:",
	"COMMON_PARTNERS" => "Partnerzy",
	
	"GALLERY_RANDOM_HEADER" => "Z galerii zdjęć",
	"GALLERY_RANDOM_MORE" => "do galerii",
	"GALLERY_MAINDIR" => "Katalog główny",
	
	"NEWS" => "Aktualności",
	
	"CONTACTFORM_HEADER" => "Formularz kontaktowy",
	"CONTACTFORM_RECEIVER" => "Adresat",
	"CONTACTFORM_TITLE" => "Tytuł wiadomości",
	"CONTACTFORM_SENDER" => "Twój Email",
	"CONTACTFORM_CONTENT" => "Treść wiadomości",
	"CONTACTFORM_SEND" => "wyślij wiadomość",
	"FORM_REQUIRED" => "Symbolem (*) oznaczono dane wymagane",
	
	"BASKET" => "Koszyk",
	"BASKET_SUMMARY_VALUETEXT" => "Wartość",
	"BASKET_SUMMARY_QUANTITYTEXT" => "Produktów",
	"BASKET_SUMMARY_VIEWCART" => "zobacz koszyk",
	"BASKET_EMPTY" => "koszyk jest pusty.",
	"BASKET_HEADER_IMAGE" => "Zdjęcie",
	"BASKET_HEADER_NAME" => "Nazwa",
	"BASKET_HEADER_PRICE" => "Cena",
	"BASKET_HEADER_QUANTITY" => "Ilość",
	"BASKET_HEADER_VALUE" => "Wartość",
	"BASKET_REMOVEITEM" => "Usuń",
	"BASKET_BOTTOM_SUMTEXT" => "Suma",
	"BASKET_BOTTOM_DISCOUNTTEXT" => "Po uwzględnieniu rabatu %DISCOUNT%% (dla towarów bez promocji)",
	"BASKET_CONTINUE" => "Kontynuuj",
	"BASKET_MAKEEMPTY" => "Opróżnij koszyk",
	"BASKET_FINALIZE" => "Finalizuj",
	"BASKET_RECOUNT" => "Przelicz",

	"ORDER" => "Realizacja zamówienia",
	"ORDER_NEW_OK_HEADER" => "Zamówienie zostało poprawnie wysłane. Na podany adres e-mail wysłano wiadomość.",
	"ORDER_NEW_ERROR_HEADER" => "Błąd przy zamówieniu",
	"ORDER_CONFIRM_OK_HEADER" => "Zamówienie zostało potwierdzone poprawnie",
	"ORDER_CONFIRM_ERROR_HEADER" => "Błąd przy potwierdzeniu zamówienia",
	"ORDER_CONFIRM_USERMISMATCH" => "Para użytkownik i nr zamówienia niezgodne",
	"ORDER_CONFIRM_NORESULTS" => "Zamówienie nie istnieje lub zostało już potwierdzone",
	"ORDER_SUMMARY_PRICETEXT" => "Całkowity koszt zamówienia %TOTALPRICE% + wybrany koszt transportu",
	"ORDER_TRANSPORTMETHODTEXT" => "Sposób transportu i zapłaty",
	"ORDER_NOTESTEXT" => "Dodatkowe instrukcje",
	"ORDER_ADDRESDATAHEADERTEXT" => "Dane adresowe zamówienia",
	"ORDER_SENDORDER" => "wyslij zamówienie",
	
	"USER_NOTLOGGEDIN" => "Nie jesteś zalogowany",
	"USER_INVOICE_DATA_HEADER" => "Dane do wystawienia faktury",
	"USER_FULLNAME" =>"Imię i nazwisko",
	"USER_COMPANYNAME" => "Nazwa firmy",
	"USER_NIP" => "Nip",
	"USER_SEND_DATA_HEADER" => "Adres wysyłki",
	"USER_LOGGEDIN_AS" => "Jesteś zalogowany jako",
	"USER_LOGIN_TITLE" => "Logowanie",
	"USER_REGISTER_TITLE" => "Rejestracja",
	"USER_LOGOUTTEXT" => "wyloguj się",
	"USER_LOGINTEXT" => "zaloguj",
	"USER_REGISTERTEXT" => "rejestracja",
	"USER_USERTEXT" => "użytkownik",
	"USER_PASSWORDTEXT" => "hasło",
	"USER_PROFILE_TITLE" => "Moje konto",
	"USER_CHANGEDATATEXT" => "zmień swoje dane lub adres wysyłki",
	"USER_EXISTS" => "użytkownik o podanym loginie już istnieje",
	"USER_PASSWORDS_DONOT_MATCH" => "podane hasła nie są jednakowe",
	
	"MODULE_RECOMMEND_HEADER" => "Poleć nas!",
	"MODULE_RECOMMEND_TEXT" => "Możecie Państwo polecić naszą stronę swoim znajomym. Wystarczy wpisać poniżej ich adres email.",
	"MODULE_RECOMMEND_EMAILTEXT" => "Podaj email",
	"MODULE_RECOMMEND_SIGNATURETEXT" => "Twój podpis",
	"MODULE_RECOMMEND_SUBMITTEXT" => "zaproś",
	"MODULE_RECOMMEND_NEWSLETTERTITLE" => "Zaproszenie na stronę",
	"MODULE_RECOMMEND_ALERTOK" => "Dziękujemy za wysłanie.",
	"MODULE_RECOMMEND_ALERTERROR" => "Żle wypełnione dane.",
	
	"MODULE_NEWSLETTER_HEADER" => "Newsletter",
	"MODULE_NEWSLETTER_TEXT" => "Jeśli chcecie być Państwo powiadamiani o nowościach na stronie prosimy poniżej zamieścić swój adres e-mail. Przycisk 'wypisz' usunie wskazany adres email z listy powiadamianych.",
	"MODULE_NEWSLETTER_NEWSLETTERTITLE" => "Rejestracja w newsletterze",
	"MODULE_NEWSLETTER_EMAILTEXT" => "Podaj email",
	"MODULE_NEWSLETTER_UNSUBMITTEXT" => "wypisz",
	"MODULE_NEWSLETTER_SUBMITTEXT" => "zapisz",
	"MODULE_NEWSLETTER_REGISTEREDALERTOK" => "Rejestracja potwierdzona.",
	"MODULE_NEWSLETTER_UNALERTOK" => "Użytkownik wypisany.",
	"MODULE_NEWSLETTER_ALERTOK" => "Dziękujemy za wysłanie.",
	"MODULE_NEWSLETTER_ALERTERROR" => "Żle wypełnione dane."	
);
?>