<!-- BEGIN NAVIGATION -->


<table class="navigation{NAVIGATION.CLASS}" width="{NAVIGATION.WIDTH}" cellspacing="1" cellpadding="2">
	<tr>
		<td>
			{NAVIGATION.ELEMENTS}
		</td>
	</tr>
</table>
<!-- END NAVIGATION -->

<!-- BEGIN NAVIGATION_HREF_ELEMENT -->
<a href="{NAVIGATION_HREF_ELEMENT.TARGET}" class="navigation_href{NAVIGATION_HREF_ELEMENT.CLASS}">
	{NAVIGATION_HREF_ELEMENT.VALUE}
</a>
<!-- END NAVIGATION_HREF_ELEMENT -->


<!-- BEGIN NAVIGATION_HREF_ELEMENT_LEFT -->
&laquo;
<!-- END NAVIGATION_HREF_ELEMENT_LEFT -->

<!-- BEGIN NAVIGATION_HREF_ELEMENT_LEFTLEFT -->
&laquo;&laquo;
<!-- END NAVIGATION_HREF_ELEMENT_LEFTLEFT -->


<!-- BEGIN NAVIGATION_HREF_ELEMENT_RIGHT -->
&raquo;
<!-- END NAVIGATION_HREF_ELEMENT_RIGHT -->

<!-- BEGIN NAVIGATION_HREF_ELEMENT_RIGHTRIGHT -->
&raquo;&raquo;
<!-- END NAVIGATION_HREF_ELEMENT_RIGHTRIGHT -->
